### ISSUE TITLE
Status of Swedish MP

### ISSUE THREAD

**Issue by salgo60** [every-politician-scrapers/sweden-riksdag-api-current#4]
Hi in the Swedish Parlament Open data model we have a status field that indicates if a person is one out of 349 people that are taking part in voting in the parlament see [Swedish Notebook](https://github.com/salgo60/open-data-examples/blob/master/Riksdagens%20ledam%C3%B6ter%20status.ipynb) , they also have a vuew that just returns 349 people see [Notebook Swedish MP status 2](https://github.com/salgo60/open-data-examples/blob/master/Riksdagens%20ledam%C3%B6ter%20status2.ipynb) 

The status are
* Tjänstgörande riksdagsledamot
* Tjänstgörande statsrådsersättare
* Tjänstgörande ersättare
* Förste vice talman (tjänstgörande riksdagsledamot)
* Andre vice talman (tjänstgörande riksdagsledamot)
* Tredje vice talman (tjänstgörande riksdagsledamot)
* Tjänstgörande talmansersättare

![image](https://user-images.githubusercontent.com/14206509/144755557-985c9603-34d3-47b1-ac6d-f8ad795a9cfa.png)

**Question 1:** Do we have something like this for other parlaments? 

**Question 2:** I feel today the SPARQL to get 349 people in the Swedish PM is rather complex. Should we do as the Swedish PM has done denormalize the data modell and make it easier?

**Question 3:** As this status is the current status it would be nice to have it in a property like current MP position and also that it will be updated rather often.... can your procedures check this?

**Comment by tmtmtmtm** [comment]
Hi @salgo60 

1: I don't understand the question. What is the 'this' referring to?

2: The SPARQL here seems fairly straightforward to me. (And, of course, it's tailored specifically to the use-case here of generating a diff against an external source, not just of getting a list of members.) How would you propose making it simpler?

3: I'm afraid I don't understand this question either. Can you explain it further?

**Comment by salgo60** [comment]
Hi 
A try to explain the **status**, the SPARQL we skip. 

![image](https://user-images.githubusercontent.com/14206509/144826689-87b9dda8-d0fd-4605-8f44-9b68307354f2.png)


The **"status"** is an explanation why you are one of 349 people in the parlament

Below some of the status you can have and **my question is do you have this for other countries?**  I think we should have this title/status also in the Swedish Wikipedia article --> if the Swedish community agree about that then we need  we need to have this "status" in Wikidata somehow.... 

* **Tjänstgörande riksdagsledamot** is the normal. You are selected in the election to be part of working in the PM
* **Tjänstgörande ersättare** is that you are not one of the 349 but you are a substitute if something is happening to on ordinary PM (like when one ordinary is on  "sick", "paternity leave", "an ordinary is selected as a minister" .....   Tjänstgörande --> that you are now ordinary because an ordinary has left
* **Tjänstgörande statsrådsersättare** you are a substitute but now ordinary because one person has left to be a minister
* **Förste vice talman (tjänstgörande riksdagsledamot)** you are a substitute but now ordinary because one person is selected to be the first speaker
* **Andre vice talman (tjänstgörande riksdagsledamot)** same as above but for the second speaker
* **Tredje vice talman (tjänstgörande riksdagsledamot)** same as above but for the third speaker
*...
  
1) In the Swedish Parlament we have [349](http://data.riksdagen.se/personlista/?iid=&fnamn=&enamn=&f_ar=&kn=&parti=&valkrets=&org=&utformat=json) people who can be part of voting
2) The open data has [one URL](http://data.riksdagen.se/personlista/?rdlstatus=samtliga&utformat=json&termlista=) for all (getting 2030 people) and [one URL](http://data.riksdagen.se/personlista/?iid=&fnamn=&enamn=&f_ar=&kn=&parti=&valkrets=&org=&utformat=json) for getting the 349 people that are selected to be part of the parlament and can vote 
3) The field I speak about is **personlista/person/status** some examples
      1) the most used is that you are ordinary --> "**Tjänstgörande riksdagsledamot**"  
            1) example [Q19977330](https://www.wikidata.org/wiki/Q19977330) [API](https://data.riksdagen.se/personlista/?iid=ed3399e1-7bce-4ea4-baf6-587f722710f5&utformat=json) / [HTML](https://www.riksdagen.se/sv/ledamoter-partier/ledamot/_ed3399e1-7bce-4ea4-baf6-587f722710f5)
            
            
![image](https://user-images.githubusercontent.com/14206509/144823635-ea5805da-3163-4665-861f-5758ba54aef1.png)

2) [Q4887285](https://www.wikidata.org/wiki/Q4887285) has in [the API](https://data.riksdagen.se/personlista/?iid=34f7ceb6-9f7c-4b37-a15e-1c61ffa639e5&utformat=json)  status = **Tjänstgörande statsrådsersättare** which is substitute for a minister. If you look in the [Html view from the parlament](https://www.riksdagen.se/sv/ledamoter-partier/ledamot/_34f7ceb6-9f7c-4b37-a15e-1c61ffa639e5) it is displayed. 
         

![image](https://user-images.githubusercontent.com/14206509/144815821-5160ae50-b7e1-47ac-9d1b-d2e88d4ed2d6.png)

**Comment by tmtmtmtm** [comment]
The closest examples I can think of are ones like Norway, where some people have a 'role' set to Q67205869, e.g. https://www.wikidata.org/wiki/Q17107262#Q17107262$0b21a445-4cad-4739-cb24-2737a48635e0 or the UK's House of Lords, with four different types of member: https://w.wiki/4WYw

I suspect the easiest approach for Sweden would be to do likewise, with a relevant [P2868](https://www.wikidata.org/wiki/Property:P2868) qualifier on the [P39](https://www.wikidata.org/wiki/Property:P39) statement.

As for this repo, its goal is compare whatever is in Wikidata with whatever can be fetched from the official API. Both sides of that are customisable: the only thing that matters is producing outputs that should be the same. I'm happy to adjust either if there's a better way to do things or there are more fields that you want to check.

**Comment by salgo60** [comment]
Excellent thanks sound like a way forward I will check with the sv;Wikipedia community what they think

Do you have any good example of Wikipedia templates that extracts those values and present them in an article...

**Comment by salgo60** [comment]
no action right now --> close this
